patterns = ["*.css", "*.lock", "tests/nvd/*.json"]
project = [
    "BACKEND",
    "CVE",
    "Csrf",
    "Cve",
    "MIDDLEWARE",
    "NVD",
    "Nvd",
    "Syncer",
    "URLCONF",
    "VALIDATORS",
    "Validator",
    "WSGI",
    "asgi",
    "clickjacking",
    "contenttypes",
    "cpe",
    "csrf",
    "cve",
    "cves",
    "cvss",
    "django",
    "djangoproject",
    "dotenv",
    "httpx",
    "nvd",
    "pydantic",
    "sendmail",
    "staticfiles",
    "syncer",
    "urlpatterns",
    "wsgi",
]

[paths]
"pyproject.toml" = ["ipdb", "ipython", "pythonpath"]
"stopple/nvd/client.py" = ["Cpe"]
"stopple_app/templates/stopple/base.html" = [
    "Buj",
    "Fv",
    "Il",
    "JLB",
    "Lze",
    "Qnuqku",
    "Zq",
    "Zw",
    "bs",
    "kx",
]
"stopple_web/settings.py" = ["DIRS", "TZ"]
"tests/nvd/cve_template.json" = ["ADDC"]

[skipped]
"stopple_app/templates/stopple/base.html" = []
