patterns = [
    "*.json",
    "*.lock",
    "LICENSE",
    "requirements.txt",
]
project = [
    "CVE",
    "Cve",
    "NVD",
    "Nvd",
    "Url",
    "Utc",
    "cve",
    "cves",
    "django",
    "lockdiff",
    "nvd",
    "reqwest",
    "serde",
    "subcommand",
    "termwidth",
    "tokio",
]

[paths]
"src/cli.rs" = ["hms"]
"src/nvd.rs" = [
    "Cpe",
    "Cvss",
    "cpe",
    "cvss",
]
"src/project.rs" = ["VR"]

[skipped]
