patterns = ["*.json", "*.lock", "LICENSE", "requirements.txt"]
project = [
    "CVE",
    "Cve",
    "NVD",
    "Nvd",
    "Url",
    "cve",
    "cves",
    "django",
    "lockdiff",
    "nvd",
    "reqwest",
    "serde",
    "subcommand",
    "termwidth",
    "tokio",
]

[paths]
"src/nvd.rs" = ["Cpe", "Cvss", "cpe", "cvss"]
"src/project.rs" = ["VR"]

[skipped]
